### ISSUE TITLE
unable to open help file: command - No such file or directory

### ISSUE THREAD

**Issue by iahung2** [lcn2/calc#104]
Either when running from the source directory or when installed. I have no idea why.

The only help command that works is `; help copyright`.

p/s: Msys2

**Comment by iahung2** [comment]
Solved. I wanted to force it to install to `/usr/local` so I used this command: `make clobber all T=/usr/local`. But later, I found the command doesn't work as expected as it still installs to `/usr`. Somehow the command affected the `calc` installation. After doing `make clobber all` and `make install` the problem is solved.

**Comment by lcn2** [comment]
See also [discussion 105](https://github.com/lcn2/calc/discussions/105) in regards to `T` and `PREFIX`.
