### ISSUE TITLE
command completion?

### ISSUE THREAD

**Issue by pmetzger** [lcn2/calc#115]
calc already depends on gnu readline, which has a programmable completion feature (see: https://tiswww.case.edu/php/chet/readline/readline.html#Custom-Completers)

This could be used for everything from completing the names of functions (or variables) being typed in to providing lists of available help files or functions.

**Comment by lcn2** [comment]
We have added this as a TODO for calc version 3.  As the TODO list links to these comments, we will now close this issue with our thanks.

p.s. We welcome any additional ideas for calc version 3 by adding comments to issue #103.
