### ISSUE TITLE
Enhancement: read/write csv

### ISSUE THREAD

**Issue by ghost** [lcn2/calc#124]
Read/Write CSV.

**Comment by lcn2** [comment]
What would be the purpose for writing CSV files?   What should happen with a CSV file is read?

Can you give a usage case for CSV file reading and writing?

**Comment by lcn2** [comment]
Sorry that you, @kcrossen, found the [above questions](https://github.com/lcn2/calc/issues/124#issuecomment-1768973146) "harsh".

**Comment by lcn2** [comment]
Would reading a CSV file into a 2D matrix, and writing a 2D matrix as a CSV file be useful?

**Comment by pmetzger** [comment]
I can't think of why I'd really want this in my desk calculator.

**Comment by lcn2** [comment]
> I can't think of why I'd really want this in my desk calculator.

Fair point, @pmetzger.

While might be able to contrive an excuse for including it, there are more important things to consider for calc v3.
