### ISSUE TITLE
Enhancement: read/write ini

### ISSUE THREAD

**Issue by ghost** [lcn2/calc#125]
Read/Write INI files.

**Comment by lcn2** [comment]
We will decline this request.

The ini file format, originally for things line windows, is intended as a configuration file.

Instead calc uses a `~/.calcrc` file to execute command at calc startup, unless `calc -q` is used.  So to configure calc, put calc commands in your `~/.calcrc` file, or wherever your $CALCRC path references.

For example:

```calc
config("tilde_space",1),;
config("fraction_space",1),;
config("complex_space",1),;
```

**Comment by lcn2** [comment]
Thanks for your suggestion.
