### ISSUE TITLE
Cant figure out how to get percent.

### ISSUE THREAD

**Issue by VladSavitsky** [lcn2/calc#13]
version 2.12.7.2
I need some help. I want to get the percent. For example: 2% from 400 = 8

```
; 400%2
	0
; 400*%2
Missing expression

; 400*2%
Missing expression

; %2*400
Missing expression

; 2%400
	2
; 
```
How to get 8?

**Comment by timocp** [comment]
Hi Vlad, in calc `%` is not for percentages, it is a modulus operator. 2 percent is 2/100, so what you want is:

```
; 400 * (2/100)
	8
```

**Comment by VladSavitsky** [comment]
Got it. Thanks.
