### ISSUE TITLE
Comma as decimal operator

### ISSUE THREAD

**Issue by robertoash** [lcn2/calc#146]
**Is your feature request related to a problem? Please describe.**
My Swedish keyboard has a comma instead of a period in the NumKeypad. It would be realldy nice to be able to configure calc to use that instead of dot as a decimal operator.

[The majority of European countries](https://www.smartick.com/blog/other-contents/curiosities/decimal-separators/) use this numbering system so I think a lot would benefit from it.

**Describe the solution you'd like**
To be able to send an argument, have calc read an environment variable or have a config file in order to replace the dot with a comma as a decimal operator. 

**Describe alternatives you've considered**
The way I see it, an environment variable would be best since this is most likely a permanent change one would want and not something that one would change on a per operation basis.

Regarding using a bare dot as a reference for the last result, this could be also configured with another environment variable. Hence, for example:
- CALC_DECIMAL_OPERATOR="comma" & CALC_LAST_RESULT_CHAR="comma" (replace both)
- CALC_DECIMAL_OPERATOR="comma" & CALC_LAST_RESULT_CHAR="dot" (replace decimal operator but not last result reference)

One could go as far as allowing to configure the character desired but I am not sure that would add much value and may even cause unwanted conflicts:
- CALC_DECIMAL_OPERATOR="§" & CALC_LAST_RESULT_CHAR="+"
- CALC_DECIMAL_OPERATOR="§" & CALC_LAST_RESULT_CHAR="+"

**Comment by lcn2** [comment]
While this issue ie closed, @robertoash, you and others are free to comment.
