### ISSUE TITLE
Bug: incorrect result (incorrect sign)

### ISSUE THREAD

**Issue by bambooleafz** [lcn2/calc#148]
The bug looks like this. Tested on termux with arm64 cpu.

![Screenshot_2024-05-26-21-04-21-828_com termux](https://github.com/lcn2/calc/assets/99185509/d3422ec7-5e2b-4fd5-b4c0-3361c65e484d)

When I enter `-0.5*log2(0.5)`, it gets the correct result. However, when doing the same operation again, the sign is incorrect

Also tested on Archlinux (x86_64), and the bug still exists.

**Comment by lcn2** [comment]
Thank you, @bambooleafz for the bug report.

We have verified that for some reason, the sign of `log2(x)` alternates:

```calc
$ calc
C-style arbitrary precision calculator (version 2.15.0.6)
Calc is open software. For license details type:  help copyright
[Type "exit" to exit, or "help" for help.]

; log2(0.5)
	-1
; log2(0.5)
	1
; log2(0.5)
	-1
; log2(0.5)
	1
```

# HELP WANTED

We are currently deal with an infrastructure emergency, so it may be a week++ before we can address this bug.  In the mean time we welcome anyone who might have a recommended patch.

**Comment by lcn2** [comment]
Thank you @bambooleafz for the bug report and fix.

We had a rapid test and verified that this bug has been fixed.

Please see [calc 2.15.0.7 release](https://github.com/lcn2/calc/releases/tag/v2.15.0.7).

**Comment by pmetzger** [comment]
BTW, did you add a regression test for bugs like this?

**Comment by lcn2** [comment]
> BTW, did you add a regression test for bugs like this?

Sorry, @pmetzger, we forgot to include the change to `cal/regress.cal` for the regression test we used to verify the fix.  Thanks for point this out!
