### ISSUE TITLE
Zero in power of evaluated zero

### ISSUE THREAD

**Issue by iamtakingiteasy** [lcn2/calc#15]
```
; 0^(0)
```

and
```
; 0^(2-2)
```

produce different results, `1` and `0` respectively on calc 2.12.7.1

With other power targets it seems to be fine:
```
; 5^(0)
```
and
```
; 5^(2-2)
```
Both produce 1.

**Comment by mattdm** [comment]
Or even:

```
; 0^(0+0)
0
; 0^(0)
1
```

**Comment by yurats** [comment]
0^0 is undefined: https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero
probably this behavior of calc is something okay-ish?

**Comment by iamtakingiteasy** [comment]
The problem is not about 0^0 being of some specific value, but about it not being consistent whether power is constant or expression.

**Comment by lcn2** [comment]
iamtakingiteasy makes a fair point in that while 0 raised to a zero power no agreed-upon value, calc was inconsistent when the zero power as a constant or an expression.

Calc defines 0^0 as 1

In the past, however, expressions such as 0^(6-6) or even 0^(0) returned 0.  This is a mis-features has been corrected in the top of master branch (2c72570).

**Comment by ValZapod** [comment]
> 0^0 is undefined: https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero

Is actually more or less defined to be 1. Limit of infinitisimal in power of infinitisimal is indeterminate form, not undefined too. See talk page...

**Comment by lcn2** [comment]
Thanks. FYI: current versions of calc return 1 for 0^0
