### ISSUE TITLE
Separate thousands with comma

### ISSUE THREAD

**Issue by Mehdi-Amrollahi** [lcn2/calc#18]
Hello,
May I know if there is any way to separate thousands (1000) with comma like 190,988,888 instead of 1909888888?

**Comment by lcn2** [comment]
Sorry, as the comma is an operator, a string such as 1,234 will produce a "Warning: Constant before comma operator" message.  One could add a printf option and an output mode to print with commas, but that would produce output that could not be used as input.  So unfortunately calc does not permit the use of commas to separate sets of 3 digits, sorry.
