### ISSUE TITLE
Seg fault caused by dereferencing null pointer when calculating sec(x) or csc(x)

### ISSUE THREAD

**Issue by wuxiuheng** [lcn2/calc#2]
While sin(x) and cos(x) prompted a "too large im(argument) for sin/cos" error, calculating sec(x) and csc(x) with x being a big complex number led to a crash.

The segfault is due to `c_sin()` (at func.c:2356) return a null pointer when input is a big complex number, which is never checked after that and finally is dereferenced in `ciszero()`. 

In `f_csc()`
```
case V_COM:
    tmp.v_type=V_COM;
    tmp.v_com=c_sin(vals[0]->v_com,err);    <—— return (complex *) 0x0
    invertvalue(&tmp,&result); 
```
In `invertvalue()`
```
invertvalue(VALUE *vp,VALUE *vres)
{
    ...
    case V_COM:         
        vres->v_com = c_inv(vp->v_com);    <—— vp->v_com is (complex *) 0x0
        return;
```

In `c_inv()`
```
c_inv(COMPLEX *c)
{   
    COMPLEX *r;
    NUMBER *q1, *q2, *den;
        
    if (ciszero(c))    <——— c is (complex *) 0x0 
```

Macro expansion of `ciszero()`
```
ciszero(c) 
cisreal(c) && qiszero((c)->real) 
qiszero((c)->imag) && qiszero((c)->real)
```
Here de-referencing `c`, which is `0x0`, causes the  segmentation fault.

Following are backtraces.
csc(2E9i)
```
commath.c:258:6: runtime error: member access within null pointer of type 'struct COMPLEX'
ASAN:DEADLYSIGNAL
=================================================================
==23131==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x556be61386f7 bp 0x7ffe458306d0 sp 0x7ffe45830690 T0)
   #0 0x556be61386f6 in c_inv commath.c:258
   #1 0x556be60862d0 in invertvalue value.c:684
   #2 0x556be5f67555 in f_csc func.c:2357
   #3 0x556be5fb1bb1 in builtinfunc func.c:9195
   #4 0x556be6000722 in o_call opcodes.c:2726
   #5 0x556be60087da in calculate opcodes.c:3918
   #6 0x556be5f3c2aa in evaluate codegen.c:293
   #7 0x556be5f3bf2a in getcommands codegen.c:223
   #8 0x556be5f3a0ad in main calc.c:619
   #9 0x7f4d1b03b2e0 in __libc_start_main (libc.so.6+0x202e0)
   #10 0x556be5f36809 in _start (calc+0x2ae809)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/wuxh/Projects/fuzz/fot/fot-fuzz/res/projects/experiments/calc/calc-analysis/commath.c:258 in c_inv
==23131==ABORTING
```

sec(2E9i)
```
commath.c:258:6: runtime error: member access within null pointer of type 'struct COMPLEX'
ASAN:DEADLYSIGNAL
=================================================================
==23218==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x55d711e2b6f7 bp 0x7ffccdd82030 sp 0x7ffccdd81ff0 T0)
   #0 0x55d711e2b6f6 in c_inv commath.c:258
   #1 0x55d711d792d0 in invertvalue value.c:684
   #2 0x55d711c5908a in f_sec func.c:2279
   #3 0x55d711ca4bb1 in builtinfunc func.c:9195
   #4 0x55d711cf3722 in o_call opcodes.c:2726
   #5 0x55d711cfb7da in calculate opcodes.c:3918
   #6 0x55d711c2f2aa in evaluate codegen.c:293
   #7 0x55d711c2ef2a in getcommands codegen.c:223
   #8 0x55d711c2d0ad in main calc.c:619
   #9 0x7f743e73b2e0 in __libc_start_main (libc.so.6+0x202e0)
   #10 0x55d711c29809 in _start (calc+0x2ae809)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/wuxh/Projects/fuzz/fot/fot-fuzz/res/projects/experiments/calc/calc-analysis/commath.c:258 in c_inv
==23218==ABORTING
```

**Comment by lcn2** [comment]
Hello,

Thank you for the bug report.  We are working in a fix using the 2.12.6.8 pre-release as a baseline.

**Comment by lcn2** [comment]
Hello,

We have a potential fix for this class of bug that we are testing for calc version 2.12.6.9.

**Comment by lcn2** [comment]
The following are the changes from calc version 2.12.6.9 to date:

    Fixed a number of core dump bugs related to the calculation of
    tan(), cot(), sec(), csc(), tanh(), coth(), sech(), and csch(),
    asin(), acos(), asinh(), acosh(), where when a call to an
    underlying function produced an invalid value.  Thanks goes to
    github user wuxiuheng for reporting this problem.

    A number of trigonometric and hyperbolic functions that incorrectly
    returned E_LOGINF, now return a new error code that is more
    specific to the trigonometric or hyperbolic function.  The
    following is a list of these new error codes: E_TAN3 E_TAN4
    E_COT3 E_COT4 E_SEC3 E_CSC3 E_TANH3 E_TANH4 E_COTH3 E_COTH4
    E_SECH3 E_CSCH3 E_ASIN3 E_ACOS3 E_ASINH3 E_ACOSH3 E_ATAN3 E_ACOT3
    E_ASEC3 E_ACSC3 E_ATANH3 E_ACOTH3 E_ASECH3 E_ACSCH3.

When calc version 2.12.6.9 is released, this issue will be fixed.

**Comment by lcn2** [comment]
FYI: Pushed the above mentioned fix to the master branch, along with some regression tests.
