### ISSUE TITLE
calc-2.12.8.0.tar.bz2 asset is missing files

### ISSUE THREAD

**Issue by sthen** [lcn2/calc#21]
Hi, the calc-2.12.8.0.tar.bz2 file added as an asset to the github release is missing most files, it only has Makefiles and a couple of empty directories.

**Comment by pmetzger** [comment]
I've seen the same problem.

**Comment by lcn2** [comment]
Hello,

We apologize for the error that resulted in a mostly empty calc-2.12.8.0.tar.bz2 file.
The problem has been corrected and regression code has been put into place in
an effort to avoid this happening again.

Please use calc version 2.12.8.1.

Thanks!

chongo (Landon Curt Noll) ^oo^

**Comment by sthen** [comment]
Great, thanks for the quick fix chongo.

**Comment by lcn2** [comment]
You are most welcome, and thank you for bringing the mistake to our attention, @sthen.
