### ISSUE TITLE
Automation broken by release URL for 2.18.8.2

### ISSUE THREAD

**Issue by pmetzger** [lcn2/calc#24]
Howdy! The source artifacts for 2.18.8.2 are located in

https://github.com/lcn2/calc/releases/download/v2.12.8.2/calc-2.12.8.2.tar.bz2

If it followed the pattern of the previous releases, it would be in:

https://github.com/lcn2/calc/releases/download/2.12.8.2/calc-2.12.8.2.tar.bz2

(Note the lack of the `v` in the second URL.)

I suspect that there was some git tag issue that caused this. It's helpful for downstream distributions using heavy automation if the pattern remains pretty consistent over time because we tend to have automated machinery to which we just feed a new version number.

**Comment by lcn2** [comment]
Hello @pmetzger,

Many apologies.  GitHub pushed us to use versions starting with v.  We left the older non-v tag on the stream, however as you point out, it changed the URLs.  I.e., we thought this was a transparent change.  Sorry!

Is it OK if we move forward with releases that begin with v?  I.e., we remain consistent going forward?

Again we apologize for this problem.

chongo (Landon Curt Noll) /\oo/\

**Comment by pmetzger** [comment]
So long as it's consistent, it can be dealt with.
