### ISSUE TITLE
2.12.9.0: typo in help/Makefile crashes the build

### ISSUE THREAD

**Issue by balducci** [lcn2/calc#26]
hi

there is a question/questions typo in help/Makefile which makes the
build of 2.12.9.0 (cloned from github) fail for me

This fixes things:

    ----8<----
    diff -c help/Makefile.FIX_QUESTIONS help/Makefile
    *** help/Makefile.FIX_QUESTIONS	Fri Mar 12 16:09:50 2021
    --- help/Makefile	Fri Mar 12 16:09:50 2021
    ***************
    *** 252,258 ****

      STD_HELP_FILES_14= credit

    ! BLT_HELP_FILES_14= contrib COPYING COPYING-LGPL question

      STD_HELP_FILES_15= wishlist todo

    --- 252,258 ----

      STD_HELP_FILES_14= credit

    ! BLT_HELP_FILES_14= contrib COPYING COPYING-LGPL questions

      STD_HELP_FILES_15= wishlist todo

    ***************
    *** 536,542 ****
                ${TRUE}; \
            fi

    ! question: ../QUESTIONS
            ${RM} -f $@
            ${CP} ../QUESTIONS $@
            ${CHMOD} 0444 $@
    --- 536,542 ----
                ${TRUE}; \
            fi

    ! questions: ../QUESTIONS
            ${RM} -f $@
            ${CP} ../QUESTIONS $@
            ${CHMOD} 0444 $@
    ***************
    *** 705,711 ****
                     ! -name mat ! -name obj.file ! -name operator \
                     ! -name overview ! -name script ! -name statement \
                     ! -name todo ! -name types ! -name unexpected \
    ! 		 ! -name variable ! -name wishlist ! -name question \
                     -print | \
               while read i; do \
                    if [ X"$$i" != X"/dev/null" ]; then \
    --- 705,711 ----
                     ! -name mat ! -name obj.file ! -name operator \
                     ! -name overview ! -name script ! -name statement \
                     ! -name todo ! -name types ! -name unexpected \
    ! 		 ! -name variable ! -name wishlist ! -name questions \
                     -print | \
               while read i; do \
                    if [ X"$$i" != X"/dev/null" ]; then \
    ***************
    *** 740,746 ****

      clean:
            ${RM} -f obj mkbuiltin funclist.c funclist.o funclist${EXT}
    ! 	${RM} -f COPYING COPYING-LGPL question

      clobber: clean
            ${RM} -f ${BLT_HELP_FILES} full .all calc
    --- 740,746 ----

      clean:
            ${RM} -f obj mkbuiltin funclist.c funclist.o funclist${EXT}
    ! 	${RM} -f COPYING COPYING-LGPL questions

      clobber: clean
            ${RM} -f ${BLT_HELP_FILES} full .all calc
    ---->8----

thanks for your valuable work

ciao

-gabriele

**Comment by lcn2** [comment]
Fixed at top of master,

Grazie mille!

chongo (Landon Curt Noll) /\oo/\
