### ISSUE TITLE
in 2.12.9.1, calcerr.c getting installed into /usr/include/calc -- is this intentional?

### ISSUE THREAD

**Issue by mattdm** [lcn2/calc#28]
In the midst of all the `.h` files, we now have a `.c`. Is this intentional?

**Comment by lcn2** [comment]
It is a bug, @mattdm thanks for reporting it.

We intend to fix it in 2.13.0.1.  In particular, the cleanup rule will remove that file.

**Comment by mattdm** [comment]
Great, thanks!

**Comment by lcn2** [comment]
The code that was checked into the top of the master branch fixes this issue.
As such it will be in the next calc release.

Thank you for reporting it, @mattdm !
