### ISSUE TITLE
Engineering mode

### ISSUE THREAD

**Issue by heitzmann** [lcn2/calc#29]
First, thanks for the work on calc! It's my go-to calculator for simple and complex stuff.

Would you be open to adding a new output mode? It is usually referred to "engineering mode" and it consists basically in representing the output in scientific notation but only using exponents that are multiples of 3 (which make it easy to translate into SI prefixes).

If so, I can give it a shot at implementing and submitting a PR.

**Comment by lcn2** [comment]
Thank you @heitzmann for your contribution.

This will be included in calc 2.14.0.0 and beyond.

**Comment by lohfu** [comment]
@lcn2 how is this mode activated? ie what do i need to do to get an answer in scientific notation?

**Comment by lohfu** [comment]
i missed reading the description in the PR, but i'm still not completely with it. how does one activate it through the config? i have tried looking for anything related in the man page, but cant find anyting

**Comment by lohfu** [comment]
ok, `help config` was my friend. sorry for the spam messages!

to anyone else reading `config("mode", "engineering")` or `config("mode", "scientific")` is what i needed
