### ISSUE TITLE
need to tag production class releases

### ISSUE THREAD

**Issue by lcn2** [lcn2/calc#43]
When a tested release has undergo and passed a quorum of qualification procedures by external groups, we
need to add a new tag to such a release.

We need to add a tag of there form:

prod-2.x.y.z to a calc v2 tested release to indicate it is "production" ready.

**Comment by lcn2** [comment]
FYI: @mattdm

**Comment by lcn2** [comment]
We need to look into that @pmetzger .. is there some documentation you suggest we should review?

**Comment by pmetzger** [comment]
https://github.com/features/actions is the start page for it. You get 2000 minutes of CI a month for free, which is probably way more than enough for a project like calc. Actual documentation is at https://docs.github.com/en/actions.

**Comment by pmetzger** [comment]
(You should be able to trigger builds + test runs off of proposed merges on pretty much every major architecture out there.)

**Comment by lcn2** [comment]
Thank you @pmetzger,

We will look into that Cl documentation and see how we can incorporate it into our release process.

In the mean time we plan to let calc 2.14.0.13 'simmer' as folks send it thru their internal pre-qualifications processes.  Once we get a 'green light' from a majority, we will test adding a prod-2.14.0.14 along with a v2.14.0.14 tags to a production release after calc 2.14.0.13 'simmers'.

In the mean time, reports and pull requests for typos are welcome for the current release.

chongo (Landon Curt Noll) /\oo/\

**Comment by lcn2** [comment]
Added tag prod-2.14.0.14 to git commit ee70c12481b94c743f19eb6a693b4a9ae3d8b919
