### ISSUE TITLE
clang error building on MacOS

### ISSUE THREAD

**Issue by artcs** [lcn2/calc#46]
I get constant errors building recent calc versions (e.g. 2.14.0.14) on MacOS 10.13 (using default makefile):

```
[...]
clang  -DCALC_SRC -DCUSTOM -Wall -Wextra -pedantic     -UUNBAN -fPIC -O3 -g3   -c -o zrandom.o zrandom.c
rm -f ver_calc
clang -DCALC_SRC -DCUSTOM -Wall -Wextra -pedantic     -UUNBAN -fPIC -DCALC_VER   version.c strl.c -o ver_calc
clang  -single_module -undefined dynamic_lookup -dynamiclib -install_name /usr/local/lib/libcalc.2.14.0.14.dylib  addop.o assocfunc.o blkcpy.o block.o byteswap.o calcerr.o codegen.o comfunc.o commath.o config.o const.o custom.o file.o func.o hash.o help.o hist.o input.o jump.o label.o lib_calc.o lib_util.o listfunc.o matfunc.o math_error.o obj.o opcodes.o pix.o poly.o prime.o qfunc.o qio.o qmath.o qmod.o qtrans.o quickhash.o seed.o sha1.o size.o str.o strl.o symbol.o token.o value.o version.o zfunc.o zio.o zmath.o zmod.o zmul.o zprime.o zrand.o zrandom.o \
	      -lreadline -lhistory -lncurses -o libcalc.2.14.0.14.dylib
ld: library not found for -lhistory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libcalc.2.14.0.14.dylib] Error 1
```

Last working release without make errors was 2.14.0.10

**Comment by pmetzger** [comment]
The "readline" package provides libhistory. I don't see a -L in your clang command line and Apple doesn't supply the readline package, so I am not sure how this would work. Perhaps you didn't configure things to find your readline installation?

**Comment by artcs** [comment]
Thank you for the hint to readline. If I set `USE_READLINE`, `READLINE_LIB`, `READLINE_EXTRAS` and `READLINE_INCLUDE` to empty in Makefile, it compiles again. I hope I remember this next release.

**Comment by pmetzger** [comment]
You might want readline support. It makes calc a lot more fun to use.

**Comment by lcn2** [comment]
We agree, @pmetzger: thank you for your explanation.

Yes, @artcs, libhistory is now default for calc.

There is a "readline" package that you may install via MacPorts ( https://www.macports.org ) or HomeBrew ( https://github.com/Homebrew/brew ).

Best wishes!

**Comment by artcs** [comment]
Thank you both. Works well with and without readline.
