### ISSUE TITLE
Segfault if getpwuid() returns NULL

### ISSUE THREAD

**Issue by baratharon** [lcn2/calc#5]
https://github.com/lcn2/calc/blob/37ad43c7fd2df394754a5d08c5d861e74f88672f/lib_calc.c#L518

An "else" is probably missing.

**Comment by lcn2** [comment]
Thank you for reporting this problem!  We will fix this in calc version 2.12.7.2.

**Comment by lcn2** [comment]
Fixed in calc version 2.12.7.2:

https://github.com/lcn2/calc/releases/tag/2.12.7.2
