### ISSUE TITLE
Variable value setting issue

### ISSUE THREAD

**Issue by kcrossen** [lcn2/calc#50]
**Describe the bug**
Under different circumstances assigning a value to a variable has different results. If the variable is assigned the value of a list member real integer 2, we get the expected results. But if the same list member is pi, we get a different (wrong) result. Freeing the variable before assignment gives the correct result in both cases.

**To Reproduce**
See attached file

**Expected behavior**
See attached file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.6.3
 - Browser Chrome
 - Version 98.0.4758.102 (Official Build) (x86_64)
 
**Smartphone (please complete the following information):**

**Additional context**
This is using calc 2.12.4.14, searching release notes for 2.14.0.15 not seeing this bug.
[Error_Report.txt](https://github.com/lcn2/calc/files/8134117/Error_Report.txt)

**Comment by lcn2** [comment]
Hello @kcrossen,

Thank you for your bug report.  We are **VERY** interested in understanding this issue.

You caught us while we were in the process of establishing our Bug report template, what you took the time top submit was the generic GitHub bug report template.  such your bug report is missing some vital information, and for this we apologize.

Please DO consider closing this bug report and reopening a new issue.  We have finished editing our bug report template.  Any feedback on the current template would be appreciated.

Again, we apologize for asking you to take the time to re-submit your bug report.  When you do re-submit, please close this bug report.

Thanks!

**Comment by kcrossen** [comment]
Have posted as #51, this post being closed.
