### ISSUE TITLE
Enhancement: Set Ctrl+C to exit if calc is not busy

### ISSUE THREAD

**Issue by donaastor** [lcn2/calc#58]
Interactive calc is an amazing tool I use very often, but I am always annoyed a little bit when I have to exit it. I have to type "quit" every time and documentation is sparse enough that I didn't manage to find a way to make a shortcut for it.

I would like to either have the ability to make a shortcut (ex. "q") for quit, that is automatically loaded whenever I execute calc, or to have Ctrl+C exit the calc. When I hit Ctrl+C I only get the message "ABORT", once. I assume this is helpful when I want to abort some calculation that takes too much time, but when there is clearly nothing to stop, it would be nice to just exit the program. I can't find the main program in the source files, so unfortunatelly, I can't make the change myself and make a pull request.

**Comment by lcn2** [comment]
What about an option (that you could set in your `.calcrc` that would control the meaning of _ Ctrl+C_?

If this were added to calc, then you could include in your `.calcrc` a line of the form:

```
config("ctrl_c", "exit"),;
```

the would cause calc to exit, instead of about, on Ctrl+C?

**Comment by donaastor** [comment]
Thank you for your extensive reply. I certainly did not know about Ctrl+D and it definitely suits my needs! I like the proposed idea for an update; I however won't pursue requiring it... In case the need for multiple key bindings catches more eyes, I would just suggest another action that is helpful to me, that is copying to the clipboard. Of course, it's maybe already implemented too.

p.s. I am sorry, I am having a little bit of a trouble exploring the capabilities of this program. Maybe having a `help all` so I can search through all pages, or having a short description for each of the source files would not take much time to make? I am not trying to nitpick, just to save some time on both ends!

**Comment by lcn2** [comment]
> Thank you for your extensive reply. I certainly did not know about Ctrl+D and it definitely suits my needs! I like the proposed idea for an update; I however won't pursue requiring it... In case the need for multiple key bindings catches more eyes, I would just suggest another action that is helpful to me, that is copying to the clipboard. Of course, it's maybe already implemented too.
> 
> p.s. I am sorry, I am having a little bit of a trouble exploring the capabilities of this program. Maybe having a `help all` so I can search through all pages would not take much time to make?

Hello @donaastor,

Try:

```calc
help full
```

For more information on help, try:

```calc
help help
```

**Comment by donaastor** [comment]
@lcn2 omg, this was embarrassing, I have no idea how I missed it... I am sorry. Thank you

**Comment by lcn2** [comment]
Closing this issue as per the discussion above.
