### ISSUE TITLE
calc v2.12.7.2 print the input twice (MINGW32 GCC)

### ISSUE THREAD

**Issue by jack6th** [lcn2/calc#6]
OS: Windows 8.1 64bit
Compiler: MINGW32 GCC
After making some very small change the source file, I compiled calc.exe successfully.
Everything is OK but calc.exe print the input twice like below.

; 9+9
9+9
　　　　　　18
; 3\*3
3\*3
　　　　　　9

**Comment by sergeevabc** [comment]
Dear @lcn2,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by lcn2** [comment]
Hello Aleksandr,

While we appreciate the intent of your request, we will not be able to comply with your request.  We have no build machines running a Microsoft operating system. Moreover, we do not agree to the Microsoft operating system licensing terms so we cannot use their operating system products.

            http://www.isthe.com/chongo/tech/comp/windoz.html

We do understand that some people use Microsoft based operating systems.  Therefore, we do carry source code that some Microsoft operating system users tell us, lets them compile calc.  We are happy to carry that code (even though we cannot test it) as long as it does not adversely impact calc overall.

We know of FREE compilers and runtime tools for Microsoft operating system users.  For example, we are told that Cygwin is a good package:

            https://www.cygwin.com

While we would encourage you to consider using other operating systems, we also know that you probably won’t do that if you haven’t already abandoned Microsoft. As a 2nd best alternative, we suggest that you install Cygwin and use that to build and run calc.  Moreover, if some Microsoft operating system user wanted to compile and distribute a calc installer for the various flavors of Microsoft operating systems, they are welcome to do so.  Calc is distributed under a license that would freely permit someone to do that.

Please do consider using other operating systems.  And if you must use a Microsoft operating system, consider installing a tool set such as Cygwin. Or get together with other Microsoft operating system users, and distribute a calc installer for the various flavors of Microsoft operating systems.

We know this answer is not likely to be very satisfactory to you.  But we wanted to be direct and let you know why we cannot comply with your request.

Sorry.
