### ISSUE TITLE
Bug: calc doesn't compile with musl libc

### ISSUE THREAD

**Issue by akdjka** [lcn2/calc#60]
Calc bug report template version: 1.2 2022-02-24

**Describe the bug**
I tried to install calc on my gentoo. Build failed, I notice a long-standing bug:
https://bugs.gentoo.org/717694
So I downloaded the latest calc from master and tried to compile. It failed the same way.

**To Reproduce**
Download the latest git variant of calc (3e4391e), make.
There is an error:
```In file included from file.c:44:
file.c: In function 'filepos2z':
fposval.h:16:54: error: 'FPOS_POS_LEN' undeclared (first use in this function); did you mean 'FILEPOS_LEN'?
   16 |         memcpy((void *)(dest), (void *)(src), sizeof(FPOS_POS_LEN))
      |                                                      ^~~~~~~~~~~~
file.c:1391:9: note: in expansion of macro 'SWAP_HALF_IN_FILEPOS'
 1391 |         SWAP_HALF_IN_FILEPOS(ret.v, &pos);
      |         ^~~~~~~~~~~~~~~~~~~~
fposval.h:16:54: note: each undeclared identifier is reported only once for each function it appears in
   16 |         memcpy((void *)(dest), (void *)(src), sizeof(FPOS_POS_LEN))
      |                                                      ^~~~~~~~~~~~
file.c:1391:9: note: in expansion of macro 'SWAP_HALF_IN_FILEPOS'
 1391 |         SWAP_HALF_IN_FILEPOS(ret.v, &pos);
      |         ^~~~~~~~~~~~~~~~~~~~
file.c: In function 'z2filepos':
file.c:1462:67: error: expected ')' before ';' token
 1462 |                 memcpy(&tmp, zpos.v, MIN(sizeof(tmp), FILEPOS_LEN);
      |                       ~                                           ^
file.c:1462:68: error: expected ';' before '}' token
 1462 |                 memcpy(&tmp, zpos.v, MIN(sizeof(tmp), FILEPOS_LEN);
      |                                                                    ^
      |                                                                    ;
 1463 |         } else {
      |         ~
file.c:60:24: warning: comparison of integer expressions of different signedness: 'long unsigned int' and 'int' [-Wsign-compare]
   60 | #define MIN(a,b) (((a) <= (b)) ? (a) : (b))
      |                        ^~
file.c:1466:38: note: in expansion of macro 'MIN'
 1466 |                 memcpy(&tmp, zpos.v, MIN(sizeof(tmp),
      |                                      ^~~
file.c:60:40: warning: operand of '?:' changes signedness from 'int' to 'long unsigned int' due to unsignedness of other operand [-Wsign-compare]
   60 | #define MIN(a,b) (((a) <= (b)) ? (a) : (b))
      |                                        ^~~
file.c:1466:38: note: in expansion of macro 'MIN'
 1466 |                 memcpy(&tmp, zpos.v, MIN(sizeof(tmp),
      |                                      ^~~
In file included from file.c:44:
fposval.h:16:54: error: 'FPOS_POS_LEN' undeclared (first use in this function); did you mean 'FILEPOS_LEN'?
   16 |         memcpy((void *)(dest), (void *)(src), sizeof(FPOS_POS_LEN))
      |                                                      ^~~~~~~~~~~~
file.c:1470:9: note: in expansion of macro 'SWAP_HALF_IN_FILEPOS'
 1470 |         SWAP_HALF_IN_FILEPOS(&ret, &tmp);
      |         ^~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:2688: file.o] Error 1
```

**Execution environment (please complete the following information):**
 - OS:
        Gentoo Linux with musl and clang

 - Calc Version
       3e4391e

**Comment by lcn2** [comment]
Hello @akdjka,

Thank you for your bug report.  We appreciate you notifying us.

Unfortunately you did not include the debug output as requested in the release process: as such we can only guess as to the problem you encountered as we do not have access to musl based Gentoo systems.

Nevertheless we are aware of some issue with the `make hsrc` header file construction in some cases, so we guess that you ran into one or more of those problems.

We published a pre-release: [calc v2.14.1.1](https://github.com/lcn2/calc/releases/tag/v2.14.1.1) that may address the problem you reported.  As such we will close this bug with both our thanks and this comment.

Please give [calc v2.14.1.1](https://github.com/lcn2/calc/releases/tag/v2.14.1.1) a try on your _Gentoo Linux with musl and clang_ system.

If that works, please add a comment to the [gentoo bug 717694](https://bugs.gentoo.org/717694) about this release.

If you run into other problems: **PLEASE** file a new bug report.  In particular please note the:

```
IMPORTANT: Please attach the output from `make debug`.
```

part of the bug report template when you file a new bug report.

Thanks!
