### ISSUE TITLE
Fix atoq and atoz cruft in LIBRARY

### ISSUE THREAD

**Issue by Leif-W** [lcn2/calc#75]
As a new user, I found this confusing.  If I were a longtime user, it may also be confusing.  If atoq and atoz have been removed or renamed, then the only acceptable references ought to be in the CHANGES file.  Submitting a pull request.

**Comment by lcn2** [comment]
We are on an eclipse expedition .. we won't be back in internet range until after 2023 May 20. Please pardon the delay ...

**Comment by lcn2** [comment]
We have corrected the LIBRARY file to refer to str2z() and str2()

Fixed obsolete references to the atoz() in LIBRARY to use the
correct internal function name of str2z().

Fixed obsolete references to the atoq() in LIBRARY to use the
correct internal function name of str2q().

These changes have been pushed to the master branch and will be part of the next release of calc.

Thank you, @Leif-W for your bug report.
