### ISSUE TITLE
Does `calc` support the `separator`?

### ISSUE THREAD

**Issue by larryw3i** [lcn2/calc#77]
Hello, @lcn2 ,
Does `calc` support the `separator`?   
Like https://peps.python.org/pep-0515/  
```bash
calc 123_456_789 + 987_654_321   
```   
Regards,
larryw3i

**Comment by larryw3i** [comment]
I think this feature should be added to `Calc`.   😭

**Comment by lcn2** [comment]
> I think this feature should be added to `Calc`. 😭

It is an idea you could propose as an enhancement. 

However not only would one have to accept constants with _'s in them, one would need to allow values to be printed via the calc `printf()` and related builtin functions as well as the calc `scanf()` builtin and related builtin functions.  One would need to determine how the "printf format" string would indicate use of _'s.  Then there is a question of come calc config parameter to indicate that the default printing of decal values should include _'s in them.

Someone would have to modify the parser, updater the released builtins, add test code to `regress.cal` to test the code, and update the help files.
