### ISSUE TITLE
Cannot configure location of ~/.calc_history

### ISSUE THREAD

**Issue by Celti** [lcn2/calc#9]
While the locations of `~/.cal` and `~/.calcrc`/`~/.calcinit` can be changed (via `CALCPATH` and `CALCRC`, respectively), `~/.calc_history` has a fixed location. It would be nice if this could be configured in the environment as well — perhaps `CALCHISTFILE`, similar to the existing `LESSHISTFILE` for `less`.

**Comment by lcn2** [comment]
I like this idea.

**Comment by lcn2** [comment]
In calc version 2.12.7.5:

By default, the calc history file is located in ~/.calc_history.
Now, if the environment variable $CALCHISTFILE is defined
and is non-empty, then calc history file will be defined
by the $CALCHISTFILE environment variable.
